### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by goodspark**
TODO: Travis + Github integration

### CODE REVIEW

**Comment by emfloyd2** [comment]
If we're open-sourcing our project, tox seems a bit heavy weight no? Are there a lot of open-source project using tox?

I'm used to seeing nose tests, vanilla unittest, or pytest with `pytest-runner` in open-source projects?

**Review by emfloyd2 — COMMENTED** [review]
If we're open-sourcing our project, tox seems a bit heavy weight no? Are there a lot of open-source project using tox?

I'm used to seeing nose tests, vanilla unittest, or pytest with `pytest-runner` in open-source projects.

**Comment by goodspark** [comment]
I can't say how many open source projects use tox, but FWIW both pytest and pytest-runner use it. The bulk of this change is because I also copied our boilerplate for things like style checks and such. If we just keep the tests and all the config gets a lot simpler, I think.

We can use any approach. As long as we have tests for both 2.7 and 3.6 🤓

**Comment by emfloyd2** [comment]
> I can't say how many open source projects use tox, but FWIW both pytest and pytest-runner use it. 

Ahhh 👍 and I like the way they bootstrap their dev environment:
https://github.com/pytest-dev/pytest/blob/master/HOWTORELEASE.rst

That works for me

**Review by emfloyd2 — APPROVED** [review]

**Pull request merged**
